disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - line_length
  - trailing_whitespace
  - identifier_name
  - unused_closure_parameter
opt_in_rules: # some rules are only opt-in
  - empty_count
  - attributes
  - closure_spacing
  - collection_alignment
  - discouraged_object_literal
  - empty_string
  - fallthrough
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_action
  - private_outlet
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Swift-Base
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

vertical_whitespace:
  severity: error
  max_empty_lines: 1

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 50
    error: 50
  validates_start_with_lowercase: true

redundant_optional_initialization:
  severity: error