version: v1.0
name: Swift-Base

agent:
  machine:
    type: a1-standard-4
    os_image: macos-xcode11

blocks:
  - name: Deploy
    task:
      env_vars:
        - name: LANG
          value: en_US.UTF-8
      secrets:
        - name: ios-base-swift-secrets
      jobs:
        - name: Staging Deploy
          commands:
            - bundle exec fastlane deploy_staging
        - name: Production Deploy
          commands:
            - bundle exec fastlane deploy_production