version: v1.0
name: Swift-Base

agent:
  machine:
    type: a1-standard-4
    os_image: macos-xcode11

blocks:
  - name: Deploy
    task:
      env_vars:
        - name: LANG
          value: en_US.UTF-8
      secrets:
        - name: ios-base-swift-secrets
      prologue:
        commands:
          - chmod 0600 ~/.ssh/id_rsa_semaphoreci
          - ssh-add ~/.ssh/id_rsa_semaphoreci

          - checkout
          - cache restore
          - bundle install --path vendor/bundle
          - cache store
      jobs:
        - name: Staging Deploy
          commands:
            - bundle exec xcversion select 11.2.1
            - bundle exec fastlane deploy_staging
        - name: Production Deploy
          commands:
            - bundle exec xcversion select 11.2.1
            - bundle exec fastlane deploy_production